# Generated by Django 2.1.5 on 2020-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_subaddition_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='toppings_count',
            field=models.IntegerField(blank=True),
        ),
    ]
