# Generated by Django 2.1.5 on 2020-02-01 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20200128_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_item', to='orders.MenuItem')),
                ('sub_additions', models.ManyToManyField(blank=True, related_name='sub_additions', to='orders.SubAddition')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
